### ISSUE TITLE
Fix broken query images

### ISSUE THREAD

**Issue by mkroetzsch** [renxiangnan/Reference_Stream_Reasoning_2016#1]
Q: The images of queries on the wiki home page are broken so that several queries are not fully visible. The queries should be given as text instead, using standard source code formatting in Markdown.

A: Thanks for this feedback, I have already replaced the broken images by the Markdown code block, thank you.

**Comment by renxiangnan** [comment]
Thanks for this feedback, I have already replaced the broken images by the Markdown code block, thank you.

**Comment by mkroetzsch** [comment]
Thanks, but please don't edit my comments to answer. You can use the text box in github to post your own comments.
